tests/unit/test_process_utils/test_async_execute_process.py

It makes the tests pass when being run in a folder with spaces for me.
@wjwwood Please review.

fix tests when run in a folder with spaces

---

docs/process_utils.rst
osrf_pycommon/process_utils/async_execute_process_asyncio.py
osrf_pycommon/process_utils/async_execute_process_trollius.py
osrf_pycommon/process_utils/execute_process_nopty.py
osrf_pycommon/process_utils/execute_process_pty.py

In Python 3.2, `close_fds` defaults to `True` whereas in Python 2.7 it defaulted to `False`. This breaks support for passing file descriptors to child processes in Python 3.2, which is required to support the GNU Make jobserver in catkin_tools (see https://github.com/catkin/catkin_tools/issues/208)
For more info, see here: https://docs.python.org/3.2/library/subprocess.html#popen-constructor
I understand that this option could be exposed to the `osrf_pycommon` API, but this PR unifies behavior between Python 2 and Python 3.
Note that while leaking file descriptors is bad, in Python 3.4 all file descriptors were made non-inheritable by default, so they still need to be explicitly flagged to be passed so subprocesses. 
For more info on this, see here: …

execute_process: Don't close all file descriptors

---

tests/test_code_format.py

Due to the following change: https://gitlab.com/pycqa/flake8/commit/1c6c1f51163784005dac358d60ecb8781d726151
http://ci.ros2.org/job/ros2_batch_ci_linux/490/testReport/tests/test_code_format/test_flake8/

fix to work with flake8 >= 2.5

---

osrf_pycommon/process_utils/execute_process_pty.py

Related to #15.
Before: http://ci.ros2.org/job/ci_windows_opensplice/694/testReport/nose.failure/Failure/runTest/
After: http://ci.ros2.org/job/ci_windows_opensplice/696/

make execute_process_pty.py importable on Windows to work with --cover-inclusive

---

stdeb.cfg

The suite list is limited by the availability of `python-trollius` and `python3-trollius`. It is available in upstream vivid, wily, xenial, and jessie, and we backported it to trusty.

add stdeb.cfg release configuration

---

osrf_pycommon/process_utils/async_execute_process.py
osrf_pycommon/process_utils/async_execute_process_asyncio/__init__.py
osrf_pycommon/process_utils/async_execute_process_asyncio/impl.py
osrf_pycommon/process_utils/async_execute_process_trollius.py
setup.py
tests/unit/test_process_utils/test_async_execute_process.py

This is the solution I've come up with to avoid errors in the post install hook when installing the Python2 debian of this package.
It avoids installing any files which use Python3 specific syntax when installing for Python2.

Do not install asyncio files for python2

---

osrf_pycommon/process_utils/async_execute_process.py
osrf_pycommon/process_utils/async_execute_process_trollius.py

This is meant to try and solve: https://github.com/catkin/catkin_tools/pull/293#issuecomment-200036885
Basically, if you `import trollius` before using `osrf_pycommon.process_utils` then it will use the trollius version of the "loop" because the trollius loop will support both trollius and asyncio, whereas asyncio does not support trollius.
@jbohren can you try to update the CI on https://github.com/catkin/catkin_tools/pull/293 to test out this change?

[process_utils] use the trollius loop if trollius has already been imported

---

osrf_pycommon/cli_utils/verb_pattern.py
tests/unit/test_cli_utils/test_verb_pattern.py

Before all arguments were considered required. With this change optional arguments are not counted when the signature length is checked,
This is required for ament/ament_tools#98 (which has already been merged and fails builds without this change).

fix detection of required arguments

---

tests/test_code_format.py

See: https://gitlab.com/pycqa/flake8/issues/179
It originally caused a job to hang on our ros2 build farm: http://ci.ros2.org/job/nightly_win_deb/184/console

work around hanging issue on Windows

---

package.xml

In order to be packaged with ament_python + bloom these build dependencies are required.

Add python build dependencies.

---

package.xml

As of https://github.com/ros2/bloom/commit/9aaf39f09d802851ee55eac394f6cd11143b4439 bloom now adds the Debian recommended python build dependencies for packages with the ament_python build type and uses debhelper magic to add `${python3:Depends}` for runtime dependencies. As such, these changes are no longer needed to package osrf_pycommon.
The long term need to explicitly depend on python for python packages can be discussed at a later date.

Python dependencies are handled by Bloom/debhelper now.

---

tests/test_code_format.py

I202 warns about newlines between groups of imports in python.
A recent change in flake8
(https://github.com/PyCQA/flake8-import-order/commit/37dafcc35eec9343641d489ac01d316cd10a6c03)
made this start showing up in osrf_pycommon.  Since we use whitespace
between imports, disable this warning in this repository.
CI: in ament/ament_lint#89
connects to ros2/build_cop#67

Add I to the list of ignored flake8 errors.

---

osrf_pycommon/process_utils/async_execute_process_asyncio/impl.py
osrf_pycommon/process_utils/async_execute_process_trollius.py
osrf_pycommon/process_utils/impl.py
tests/unit/test_process_utils/impl_aep_protocol.py

This bugfixes a problem in [osrf_pycommon/process_utils/async_execute_process_asyncio/impl.py#L67-L68](https://github.com/osrf/osrf_pycommon/blob/1db811bff17400e5e5402ddb6fa1dc786bf63cf5/osrf_pycommon/process_utils/async_execute_process_asyncio/impl.py#L67-L68) which fails when operating on a  protocol class that only uses keyword arguments. 
See [ros2/launch/issues/188](https://github.com/ros2/launch/issues/188#issuecomment-466262043) for more details. The traceback there if tty is enabled, which triggers this code:
```
Traceback (most recent call last):
File "/opt/ros/crystal/lib/python3.6/site-packages/launch/actions/execute_process.py", line 423, in __execute_process
stderr_to_stdout=(self.__output == 'screen'),
File "/opt/ros/crystal/lib/python3.6/site-packages/osrf_pycommon/process_u …
```

Use keyword arguments only for protocol_class invocations

---

osrf_pycommon/cli_utils/verb_pattern.py
tests/unit/test_cli_utils/test_verb_pattern.py

Fixed two simple deprecation warnings as outlined in #61. The main deprecation warning, however, requires a bit more work since they have an issue with the `yield` function used within the `async def`.

fixed simple deprecation warnings (issue #61)

---

osrf_pycommon/terminal_color/windows.py

This started making Travis CI builds fail.  I have no idea why they just started failing now, but in any case this code looks wrong, so this should fix it.

Fix the __str__ method for windows terminal_color.

---

.travis.yml
osrf_pycommon/process_utils/async_execute_process_asyncio/impl.py

In later versions of Python, @asyncio.coroutine is deprecated
in favor of "async def".  However, in order to support python
back to 3.6, we also have to switch from using "yield from"
to instead using "await".
Note that according to the [Python documentation](https://docs.python.org/3.5/library/asyncio-task.html), this should work all the way back to Python 3.5.  But this definitively breaks support for Python 2, so I've removed it from Travis.

Remove deprecated use of asyncio.coroutine decorator.

---

stdeb.cfg

See: https://github.com/osrf/osrf_pycommon/pull/64#issuecomment-648311606

remove jessie because we no longer support 3.4

---

stdeb.cfg

Both provide the same files. This is needed to upgrade from Ubuntu 18 to
20.

Python 2/3 version conflict

---

osrf_pycommon/process_utils/get_loop_impl.py

On Windows, avoid loops closing during garbage collection and reuse existing ones if possible.
Connected to https://github.com/ros2/launch/pull/476.

Fix osrf.py_common.process_utils.get_loop() implementation

---

stdeb.cfg

`python-osrf-pycommon` and `python3-osrf-pycommon` should conflict in both directions, currently the conflict is only added to the python 3 package. (They conflict because both install the same `package.xml` and `ament_index` file.)

add missing conflict to stdeb.cfg

---

stdeb.cfg

* Drop Ubuntu Xenial and surrounding non-LTS distributions
* Drop Debian Stretch which is no longer supported upstream
* Add Debian Bullseye
* Add Ubuntu Jammy

Update release distributions.

---

.travis.yml
README.md
osrf_pycommon/cli_utils/verb_pattern.py
package.xml
setup.py
stdeb.cfg

Replace it with the use of the more modern importlib*
libraries.  There are a couple of reasons to do this:
1.  pkg_resources is quite slow to import; on my machine,
just firing up the python interpreter takes ~35ms, while
firing up the python interpreter and importing pkg_resources
takes ~175ms.  Firing up the python interpreter and importing
importlib_metadata takes ~70ms.  Removing 100ms per invocation
of the command-line both makes it speedier for users, and
will speed up our tests (which call out to the command-line
quite a lot).
2.  pkg_resources is somewhat deprecated and being replaced
by importlib.  https://importlib-metadata.readthedocs.io/en/latest/using.html
describes some of it
See ros2/ros2#919 for a lot more …

Remove use of pkg_resources from osrf_pycommon.

---

README.md
stdeb.cfg

Related to https://github.com/osrf/osrf_pycommon/pull/66

limit 1.0.x to < focal, due to new dependency available in >= focal only

---

stdeb.cfg

Debian Buster is still on Python 3.7: https://packages.debian.org/buster/python3
and thus is not supported by the 2.x releases.

Continue releasing 1.0.x on Debian Buster.

---

stdeb.cfg

Debian Buster is on Python 3.7: https://packages.debian.org/buster/python3
In order to complete this I believe we'll also need to yank osrf-pycommon 2.0.0-1 from the bootstrap ROS and ROS 2 repositories unless we decide to add a Debian epoch which I think is unnecessary.

Don't release 2.x / master on Debian Buster.

---

osrf_pycommon/cli_utils/verb_pattern.py

Use the newer select interface where available, but fallback
to the dict interface as needed.
Connects to https://github.com/ros2/ros2/issues/1254

Fix an importlib_metadata warning with Python 3.10.

---

setup.py

Adding a test dependency on 'pytest' will cause colcon to use pytest when running the package's tests, which yields a better experience than the existing fallback to unittest.

Declare test dependencies in [test] extra

---

.github/workflows/ci.yaml

Following pattern, stop using `ubuntu-latest` and do Python 3.6 testing on 20.04, since 18.04 is EOL.

Update supported platforms

---

stdeb.cfg

This will need a release or manual flood to deploy.

Add bookworm as a python3 target

---

osrf_pycommon/process_utils/get_loop_impl.py

The previous patch that did this only did it for one of the cases, but we actually need to catch this warning for all cases of get_event_loop().  Do that here by wrapping the entire block in catch_warnings().  With this in place, other spurious warnings from downstream packages (like launch) are also quieted.
@cottsay @Voldivh FYI

Catch all of the spurious warnings from get_event_loop.

---

osrf_pycommon/process_utils/execute_process_nopty.py
tests/unit/test_process_utils/impl_aep_asyncio.py

Resolve outstanding resource warnings when running tests

---

.github/workflows/ci.yaml

Python version 3.7 is no longer supported as of June 27, 2023

Updated python version

---

stdeb.cfg

I'd like to get ahead of these issues instead of rushing to mitigate them when things go awry.
Using a debian version suffix which falls late alphabetically appears to give our packages preference by apt. If a user enables a repository which distributes packages created by OSRF or ROS, it is likely that they wish to use these packages instead of the ones packaged by their platform.
Requires ros-infrastructure/ros_release_python#42

Add '+upstream' suffix to published deb version

---

stdeb.cfg

Regardless of what suites we target, it would be nice if the same requirements were expressed in both metadata formats.
Follow-up to #81 and #66

Align stdeb dependencies with setup.py

---

osrf_pycommon/cli_utils/verb_pattern.py

After 11 years: https://github.com/osrf/osrf_pycommon/blame/94b0d8e89a4000db8bee7b1c70dd8772a20b6229/osrf_pycommon/cli_utils/verb_pattern.py#L112

Fix typo in verbs help output

---

setup.py

FIX:
#SetuptoolsDeprecationWarning: License classifiers are deprecated. !!
******************************************************************************** Please consider removing the following classifiers in favor of a SPDX license expression:
License :: OSI Approved :: Apache Software License
See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details. ********************************************************************************

Fix setuptools deprecations
